### ISSUE TITLE
Стилизация примера

### ISSUE THREAD

**Issue by Melanitski** [Rademade/angular-cycle-gallery#12]
1. Кнопку home показывать всегда

2. Добавить текста на каждый слайд: 
2.1 "Click next or swipe for smooth animation"
2.2 "Click next for instant animation"
2.3 "One more example"

3. Добавить кнопку "How implement this example"

**Comment by maxshutyak** [comment]
Готово можно проверить на продакшине

**Comment by maxshutyak** [comment]
Я не делал посмотреть пример прям на сайте галереи так как нужно подключать библиотеку еще одну для подстветки кода в браузере. При нажатии на view code будет перенаправлять на github

**Comment by maxshutyak** [comment]
.
